M48
; DRILL file {KiCad 8.0.1} date 2024-06-15T11:10:31+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-15T11:10:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X135.128Y-68.072
X135.128Y-134.366
X189.103Y-68.072
X189.103Y-134.239
M30
